NWEEI/NWEEI/Models/CustomError.cs
using System.ComponentModel.DataAnnotations;

namespace NWEEI.Models
{
    public class CustomError
    {
        private string message { get; set; }
        public CustomError(string ErrorMessage) => message = ErrorMessage;
        public string GetErrorMessage() => message;
        public void SetErrorMessage(string ErrorMessage) => message = ErrorMessage;
    }
}

NWEEI/NWEEI/Models/Notification.cs
using System.ComponentModel.DataAnnotations;

namespace NWEEI.Models
{
    public class Notification
    {
        private string Message { get; set; }
        public Notification(string message) => Message = message;
        public string GetMessage() => Message;
        public void SetMessage(string message) => Message = message;
    }
}

NWEEI/NWEEI/Controllers/FAQController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using NWEEI.Data;
using NWEEI.Models;
using NWEEI.Repositories;
using NWEEI.ViewModels;

namespace NWEEI.Controllers
{
    public class FAQController : Controller
    {
        IFAQRepo repo;
        ICategoryRepo catRepo;

        public FAQController(IFAQRepo r, ICategoryRepo cr)
        {
            repo = r;
            catRepo = cr;
        }
        
        // GET: FAQ
        public async Task<IActionResult> Index()
        {
            ViewBag.Current = "Resources";

            return View(repo.GetFAQCategories());
        }

        // get all FAQs
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Manage()
        {
            return View(repo.FAQs.ToList());
        }

        // get all FAQs in a category
        public async Task<IActionResult> ByCategory(int categoryID)
        {
            ViewBag.Current = "Resources";

            // only return published FAQs
            return View(repo.GetPublishedFAQsByCategoryID(categoryID));
        }

        // GET: FAQ/Details/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Details(int? id)
        {
            ViewBag.Current = "Resources";

            if (id == null)
            {
                return NotFound();
            }

            FAQ fAQ = repo.FAQs
                .FirstOrDefault(m => m.FAQID == id);
            if (fAQ == null)
            {
                return NotFound();
            }

            return View(fAQ);
        }

        // GET: FAQ/Create
        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            // get categories
            List<Category> categories = repo.GetAllCategories();

            // initialize new category selector VM
            CategorySelectorViewModel viewModel = new CategorySelectorViewModel
            {
                Categories = categories,
                CurrentFAQ = new FAQ
                {
                    Category = new Category
                    {
                        Name = ""
                    }
                }
            };

            return View(viewModel);
        }

        // POST: FAQ/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Create(CategorySelectorViewModel viewModel)
        {
            FAQ faq = new FAQ();

            if (ModelState.IsValid)
            {
                // create new FAQ with viewModel values
                faq.Question = viewModel.CurrentFAQ.Question;
                faq.Answer = viewModel.CurrentFAQ.Answer;
                faq.IsPublished = viewModel.CurrentFAQ.IsPublished;
                faq.Featured = viewModel.CurrentFAQ.Featured;
                faq.Category = catRepo.GetCategoryByID(viewModel.CurrentFAQ.Category.CategoryID);

                repo.AddFAQ(faq);
                return RedirectToAction(nameof(Manage));
            }
            return View(viewModel);
        }

        // GET: FAQ/Edit/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            // get FAQ
            FAQ faq = repo.GetFAQByID((int)id);
            if (faq == null)
            {
                return NotFound();
            }

            // get categories
            List<Category> categories = repo.GetAllCategories();

            // initialize new category selector VM
            CategorySelectorViewModel viewModel = new CategorySelectorViewModel
            {
                Categories = categories,
                CurrentCategory = faq.Category,
                CurrentFAQ = faq
            };

            return View(viewModel);
        }

        // POST: FAQ/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int id, CategorySelectorViewModel viewModel)

        {
            if (id != viewModel.CurrentFAQ.FAQID)
            {
                return NotFound();
            }

            // get existing FAQ with id
            FAQ faq = repo.GetFAQByID(id);

            if (ModelState.IsValid)
            {
                // update existing FAQ's values with viewModel values
                faq.Question = viewModel.CurrentFAQ.Question;
                faq.Answer = viewModel.CurrentFAQ.Answer;
                faq.IsPublished = viewModel.CurrentFAQ.IsPublished;
                faq.Featured = viewModel.CurrentFAQ.Featured;
                faq.Category = repo.GetAllCategories()
                    .Where(c => c.CategoryID == viewModel.NewCategoryID)
                    .FirstOrDefault();

                try
                {
                    repo.UpdateFAQ(faq);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FAQExists(viewModel.CurrentFAQ.FAQID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Manage));
            }
            return View(viewModel);
        }

        // GET: FAQ/Delete/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var fAQ = await repo.FAQs
                .FirstOrDefaultAsync(m => m.FAQID == id);
            if (fAQ == null)
            {
                return NotFound();
            }

            return View(fAQ);
        }

        // POST: FAQ/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            FAQ faq = repo.GetFAQByID((int)id);
            repo.DeleteFAQ(faq);
            return RedirectToAction(nameof(Manage));
        }

        private bool FAQExists(int id)
        {
            return repo.FAQs.Any(e => e.FAQID == id);
        }
    }
}

NWEEI/NWEEI/Views/Shared/Components/QuickArticles/QuickArticlesViewComponent.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using NWEEI.Models;
using NWEEI.Repositories;

namespace NWEEI.Views.Shared.Components.QuickArticles
{
    public class QuickArticlesViewComponent : ViewComponent
    {
        List<Article> topArticles;
        IResourceRepo repo;

        public QuickArticlesViewComponent(IResourceRepo r)
        {
            repo = r;
        }

        // takes a string whichArticles that specifies the type of articles to retrieve
        public async Task<IViewComponentResult> InvokeAsync(string whichArticles)
        {
            topArticles = await GetItemsAsync(whichArticles);
            return View(topArticles);
        }

        private async Task<List<Article>> GetItemsAsync(string whichArticles)
        {
            List<Article> articles = new List<Article>();

            // use whichArticles to determine which repo method to call
            if (whichArticles == "NWEEI News")
            {
                articles = repo.GetFeaturedNWEEINewsArticles();
            }
            else if (whichArticles == "Industry News")
            {
                articles = repo.GetFeaturedIndustryNewsArticles();
            }

            return articles;
        }
    }
}

NWEEI/NWEEI/Views/Shared/CustomError.cshtml
@model NWEEI.Models.CustomError
<h1 class="text-danger">Error:</h1>
<h3 class="text-danger">@Model.GetErrorMessage()</h3>
<hr />
<a class="btn btn-primary" href="javascript:void(0);" onclick="history.go(-1);">Go Back</a>

NWEEI/NWEEI/Views/Shared/Notification.cshtml
@model NWEEI.Models.Notification
<h3>@Model.GetMessage()</h3>
<hr />
<a class="btn btn-primary" asp-action="Index" asp-controller="Home">Home</a>

NWEEI/NWEEI/Views/Shared/_Layout.cshtml
@using NWEEI.ViewModels

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - NWEEI</title>
    <link rel="icon" type="image/x-icon" href="~/images/NWEEI-favicon.png" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />

    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/Staff.css" />
    <link rel="stylesheet" href="~/css/org.css" />
    <link rel="stylesheet" href="~/css/article.css" />
    <link rel="stylesheet" href="~/css/accordion.css" />
    <link rel="stylesheet" href="~/css/program.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"> @*icons*@
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"> @*icons*@
</head>
<body>
    <header>

        <!-- swoop and hero image -->
        <div class="header-content">
            <!-- swoopy -->
            <img class="swoop" src="~/images/NWEEI-Wave.png" />

            <!-- logo -->
            <img class="logo" src="~/images/NWEEI-logo_white.png" />

            <!-- short description, contact form, and call button -->
            <div class="header-info">
                <div class="header-desc">Education & Training for Energy & Water Professionals</div>

                <div class="mt-1">
                    <div class="header-search">

                        <!-- search bar begin -->
                        <form method="post">
                            <div class="form-group mb-0">
                                <!-- search input and icon -->
                                <div class="search-bar-content">

                                    @{
                                        // create SearchViewModel object and if input is given, assign it to SearchQuery property
                                        SearchViewModel viewModel = new SearchViewModel();
                                    }
                                    <!-- search input -->
                                    <input asp-for="@viewModel.SearchQuery" class="form-control header-search-bar" placeholder="Search NWEEI..." />

                                    <!-- icon -->
                                    <span class="search-submit">
                                        <button type="submit"
                                                asp-controller="Resources" asp-action="Index"
                                                style="background: none; color: inherit; border: none; padding: 0; font: inherit; cursor: pointer; outline: inherit; position: absolute;">
                                            <i type="submit" class="fa fa-search mr-2"></i>
                                        </button>
                                    </span>
                                </div>
                            </div>
                        </form>
                        <!-- search bar end -->

                    </div>
                    
                    <hr class="header-divider" />

                    <!-- call icon -->
                    <div class="header-phone">
                        <a class="phone-button" href="tel:5415567724"><i type="submit" class="fa fa-phone"></i></a>
                    </div>

                    <!-- email icon -->
                    <div class="header-phone">
                        <a class="phone-button" asp-action="ContactUs" asp-controller="About"><i type="submit" class="fa fa-envelope"></i></a>
                    </div>

                </div>
            </div>
            <!-- placeholder hero carousel -->
            @if (ViewBag.Current == "Degrees")
            { 
                <div id="heroCarousel" class="carousel slide hero" data-ride="carousel">
                    <div class="carousel-inner">
                        <div class="carousel-item active">
                            <img class="" src="~/images/lightning_bolts_needles_1024.jpg" alt="Lightning on the Water">
                        </div>
                        <div class="carousel-item">
                            <img src="/images/header_slideshowimages/default/IMG_4350.jpg" alt="A group of people standing in front of a fence near vegitation">
                        </div>
                        <div class="carousel-item">
                            <img src="/images/header_slideshowimages/default/IMG_8855.jpg" alt="People hold and observing funnels on a lawn">
                        </div>
                    </div>
                </div>
            }
            else
            {
                <img class="hero" src="~/images/lightning_bolts_needles_1024.jpg" />
            }
                <!-- placeholder hero image -->
        </div>

        <!-- BEGIN NAVIGATION -->
        <nav>
            <!-- top-level navigation menu -->
            <div class="navigation">
                <span>
                    <a class="text-dark" asp-controller="Home" asp-action="Index">
                        Home
                    </a>
                </span>
                <span>
                    <a class="text-dark" asp-controller="About" asp-action="Index">
                        About
                    </a>
                </span>
                <span>
                    <a class="text-dark" asp-controller="Programs" asp-action="Degrees">
                        Degrees
                    </a>
                </span>
                <span>
                    <a class="text-dark" asp-controller="Programs" asp-action="ProfessionalDevelopment">
                        Professional Development
                    </a>
                </span>
                <span>
                    <a class="text-dark" asp-controller="Resources" asp-action="Index">
                        Resources
                    </a>
                </span>
                <span>
                    <a class="text-dark" asp-controller="Registration" asp-action="Create">
                        Register!
                    </a>
                </span>
            </div>

            <!-- sub navigation menu (dynamic) -->
            <div class="sub-navigation">
                @if (ViewBag.Current == "About")
                {
                    <span>
                        <a class="text-dark" asp-controller="About" asp-action="Contact">
                            Contact & Location
                        </a>
                    </span>
                    <span>
                        <a class="text-dark" asp-controller="About" asp-action="History">
                            Mission & History
                        </a>
                    </span>
                    <span>
                        <a class="text-dark" asp-controller="About" asp-action="Instructors">
                            Instructors
                        </a>
                    </span>
                    <span>
                        <a class="text-dark" asp-controller="About" asp-action="Staff">
                            Staff
                        </a>
                    </span>
                }
                else if (ViewBag.Current == "Degrees")
                {
                    /*
                    // not a currently valid degree
                    <span>
                        <a class="text-dark" asp-controller="Programs" asp-action="EnergyMgmt">
                            Energy Management
                        </a>
                    </span>
                    */

                    <span>
                        <a class="text-dark" asp-controller="Programs" asp-action="EMBC">
                            Energy Management with Building Controls
                        </a>
                    </span>
                    <span>
                        <a class="text-dark" asp-controller="Programs" asp-action="WaterConservation">
                            Water Conservation
                        </a>
                    </span>
                }
                else if (ViewBag.Current == "Professional Development")
                {
                    <span>
                        <a class="text-dark" asp-controller="Programs" asp-action="BOC">
                            Building Operator Certification
                        </a>
                    </span>
                    <span>
                        <a class="text-dark" asp-controller="TrainingProgram" asp-action="CustomTraining">
                            Custom Training
                        </a>
                    </span>
                }
                else if (ViewBag.Current == "Resources")
                {
                    <span>
                        <a class="text-dark" asp-controller="Resources" asp-action="NWEEINews">
                            NWEEI News
                        </a>
                    </span>
                    <span>
                        <a class="text-dark" asp-controller="Resources" asp-action="IndustryNews">
                            Industry News
                        </a>
                    </span>

                    /*
                    // not currently active
                    <span>
                        <a class="text-dark" asp-controller="Resources" asp-action="Index">
                            Jobs
                        </a>
                    </span>
                    */

                    <span>
                        <a class="text-dark" asp-controller="Resources" asp-action="CareerMap">
                            Career Map
                        </a>
                    </span>
                    <span>
                        <a class="text-dark" asp-controller="Resources" asp-action="IndustryAssociations">
                            Industry Assocations
                        </a>
                    </span>
                    <span>
                        <a class="text-dark" asp-controller="Category" asp-action="Index">
                            Articles
                        </a>
                    </span>
                    <span>
                        <a class="text-dark" asp-controller="FAQ" asp-action="Index">
                            FAQs
                        </a>
                    </span>
                }
            </div>
        </nav>
        <!-- END NAVIGATION -->

    </header>

    <!-- PAGE CONTENT CONTAINER -->
    <div class="main-content-container">
        <div class="main-content-inner container">
            <main role="main" class="pb-3">
                @RenderBody()
            </main>
        </div>
    </div>
    <!-- END PAGE CONTENT CONTAINER -->

    <!-- sticky dashboard button -->
    <div class="sticky-dash-icon">
        <a asp-controller="Home" asp-action="Dashboard" style="color: #6cb3ea;">
            <i class="fa-solid fa-user-gear"></i>
            @*<i class="fa-solid fa-user-pen"></i>*@
            @*<i class="fa-regular fa-wrench"></i>*@
            @*<i class="fa-solid fa-screwdriver-wrench"></i>*@
        </a>
    </div>

    <!-- FOOTER -->
    <footer class="border-top footer text-muted bg-dark fixed-bottom">
        <div class="container">
            <partial name="_LoginPartial" />
        </div>
    </footer>
    <!-- END FOOTER -->

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script>
        $('.carousel').carousel({
              interval: 10000
        })
    </script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>