NWEEI/NWEEI/Models/CustomTrainingOption.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace NWEEI.Models
{
    public class CustomTrainingOption
    {
        private List<TrainingDetail> trainingDetails = new List<TrainingDetail>();

        public int CustomTrainingOptionID { get; set; }

        [Required(ErrorMessage = "Custom training option name is required.")]
        public string Name { get; set; }

        public List<TrainingDetail> TrainingDetails { get { return trainingDetails; } }
    }

    public class TrainingDetail
    {
        public TrainingDetail() { }

        public TrainingDetail(string detail) { Detail = detail; }

        public int TrainingDetailID { get; set; }

        public string Detail { get; set; }

        [ForeignKey("TrainingOptionID")]
        public CustomTrainingOption TrainingOption { get; set; }
    }
}

NWEEI/NWEEI/Models/TrainingProgram.cs
using System.ComponentModel.DataAnnotations;

namespace NWEEI.Models
{
    public class TrainingProgram
    {

        public int TrainingProgramID { get; set; }
        [Required(ErrorMessage = "Please enter a name for the Training Program.")]
        public string Name { get; set; }
    }
}

NWEEI/NWEEI/Controllers/TrainingProgramController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using NWEEI.Models;
using NWEEI.Repositories;

namespace NWEEI.Controllers
{
    public class TrainingProgramController : Controller
    {
        private ITrainingProgramRepo repo;

        public TrainingProgramController(ITrainingProgramRepo r) => repo = r;

        // GET: TrainingProgram
        [Authorize(Roles = "Admin")]
        public IActionResult Index() => View(repo.GetAllTrainingPrograms());

        // GET: TrainingProgram/Details/5
        [Authorize(Roles = "Admin")]
        public IActionResult Details(int? id)
        {
            if (id is null) return NotFound();
            TrainingProgram trainingProgram = repo.GetTrainingProgramByID((int)id);
            return trainingProgram is null ? NotFound() : View(trainingProgram);
        }

        // GET: TrainingProgram/Create
        [Authorize(Roles = "Admin")]
        public IActionResult Create() => View();

        // POST: TrainingPrograms/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public IActionResult Create([Bind("TrainingProgramID,Name")] TrainingProgram trainingProgram)
        {
            if (!ModelState.IsValid) return View(trainingProgram);
            repo.AddTrainingProgram(trainingProgram);
            return RedirectToAction(nameof(Index));
        }

        // GET: TrainingProgram/Edit/5
        [Authorize(Roles = "Admin")]
        public IActionResult Edit(int? id)
        {
            if (id is null) return NotFound();
            TrainingProgram trainingProgram = repo.GetTrainingProgramByID((int)id);
            return trainingProgram is null ? NotFound() : View(trainingProgram);
        }

        // POST: TrainingProgram/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public IActionResult Edit(int id, [Bind("TrainingProgramID,Name")] TrainingProgram trainingProgram)
        {
            if (id != trainingProgram.TrainingProgramID) return NotFound();

            if (!ModelState.IsValid) return View(trainingProgram);
            try
            {
                repo.UpdateTrainingProgram(trainingProgram);
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!TrainingProgramExists(trainingProgram.TrainingProgramID))
                    return NotFound();
                else throw;
            }
            return RedirectToAction(nameof(Index));
        }

        // GET: TrainingProgram/Delete/5
        [Authorize(Roles = "Admin")]
        public IActionResult Delete(int? id)
        {
            if (id is null) return NotFound();
            TrainingProgram trainingProgram = repo.GetTrainingProgramByID((int)id);
            return trainingProgram is null ? NotFound() : View(trainingProgram);
        }

        // POST: Tag/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public IActionResult DeleteConfirmed(int id)
        {
            TrainingProgram trainingProgram = repo.GetTrainingProgramByID(id);
            repo.DeleteTrainingProgram(trainingProgram);
            return RedirectToAction(nameof(Index));
        }

        private bool TrainingProgramExists(int id) =>
            repo.TrainingPrograms.Any(e => e.TrainingProgramID == id);


        #region CustomTrainingOption methods

        public async Task<IActionResult> CustomTraining()
        {
            ViewBag.Current = "Professional Development";
            return View(repo.GetCustomTrainingOptions());
        }

        public async Task<IActionResult> CustomTrainingOption(int id)
        {
            ViewBag.Current = "Professional Development";
            return View(repo.GetCustomTrainingOptionByID(id));
        }

        #endregion
    }
}

NWEEI/NWEEI/Views/TrainingProgram/Create.cshtml
@model NWEEI.Models.TrainingProgram

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>TrainingProgram</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

NWEEI/NWEEI/Views/TrainingProgram/CustomTraining.cshtml
@model List<CustomTrainingOption>

@{
    ViewData["Title"] = "Custom Training Options";
}


<!-- program title and image -->
<div>
    <div class="custom-training program-header">
        <div class="program-title">Custom Training</div>
    </div>
</div>

<!-- program overview -->
<div class="container content-section">
    <h3>Custom Training Options</h3>
    <p>
        NWEEI utilizes instructors from an expansive network of industry experts to provide
        training nationally and internationally. We customize and create programs for our
        participants that are tailored to meet specific educational demand. These programs
        can cover a wide range of efficiency topics and can be delivered utilizing on-site
        facilities, remote locations and virtually online.
    </p>

    <p class="text-center pt-2 font-weight-bold mb-0">
        <a asp-controller="About" asp-action="ContactUs">
            Contact NWEEI to build your custom training program.
        </a>
    </p>
</div>

<!-- custom training option tiles -->
<div class="dark-block">
    <div class="container">
        <div class="content-section">
            <h5 class="text-center pb-3">Select one of NWEEI's custom training options to learn more:</h5>
            <div class="container tiles" style="width: 83%;">

                @foreach (CustomTrainingOption trainingOption in Model)
                {
                    <a class="tile-link" asp-controller="TrainingProgram"
                       asp-action="CustomTrainingOption" asp-route-id="@trainingOption.CustomTrainingOptionID">
                        <div class="tile-container">
                            <span class="tile-content">
                                @trainingOption.Name
                            </span>
                        </div>
                    </a>
                }

            </div>
        </div>
    </div>
</div>

<!-- contact options -->
<div class="container content-section text-center">
    <h5 class="text-center">Contact NWEEI to build your custom training program.</h5>

    <!-- buttons -->
    <div class="container w-75">
        <div class="button-group row">
            <a class="btn btn-primary" asp-controller="About" asp-action="ContactUs">Contact Us</a>
        </div>
    </div>
</div>

NWEEI/NWEEI/Views/TrainingProgram/CustomTrainingOption.cshtml
@model CustomTrainingOption

@{
    ViewData["Title"] = Model.Name;
}

<div class="custom-breadcrumb">
    <a asp-controller="TrainingProgram" asp-action="CustomTraining">
        <span class="breadcrumb-icon"><i class="fa fa-chevron-left" aria-hidden="true"></i></span>
        <span class="breadcrumb-name">Back to Custom Training</span>
    </a>
</div>

<div>
    <!-- custom training option header: name, edit option -->
    <div>
        <div class="text-center mb-4">
            <h1>@Model.Name</h1>
        </div>
        <div class="content-header">
            @*
                TODO: uncomment when custom training edit functionality has been built out
                <!-- admin edit button -->
                if (User.IsInRole("Admin"))
                {
                    <span class="admin-action-button btn btn-primary">
                        <a asp-action="Edit" asp-route-id="@Model.ArticleID">Edit Article</a>
                    </span>
                }
            *@
        </div>
    </div>
</div>

<!-- training details -->
<div class="dark-block">
    <div class="container">
        <div class="content-section">

            <h4 class="text-center">The @Model.Name training option includes:</h4>

            <div class="container">
                <ul class="training-details">

                    @foreach (TrainingDetail detail in Model.TrainingDetails)
                    {
                        <li>@detail.Detail</li>
                    }
                </ul>
            </div>

        </div>
    </div>
</div>

<!-- contact options -->
<div class="container content-section text-center">
    <h5 class="text-center">Contact NWEEI to build your custom training program.</h5>

    <!-- buttons -->
    <div class="container w-75">
        <div class="button-group row">

            <a class="btn btn-primary" asp-controller="About" asp-action="ContactUs">Contact Us</a>

            @*
            <a href="tel:5415567724" class="btn btn-primary">Call Now</a>

            <!-- TODO: link to email -->
            <a href="#" class="btn btn-primary">Email Us</a>
            *@
        </div>
    </div>
</div>

NWEEI/NWEEI/Views/TrainingProgram/Delete.cshtml
@model NWEEI.Models.TrainingProgram

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>TrainingProgram</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="TrainingProgramID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

NWEEI/NWEEI/Views/TrainingProgram/Details.cshtml
@model NWEEI.Models.TrainingProgram

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>TrainingProgram</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.TrainingProgramID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

NWEEI/NWEEI/Views/TrainingProgram/Edit.cshtml
@model NWEEI.Models.TrainingProgram

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>TrainingProgram</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="TrainingProgramID" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

NWEEI/NWEEI/Views/TrainingProgram/Index.cshtml
@model IEnumerable<NWEEI.Models.TrainingProgram>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.TrainingProgramID">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.TrainingProgramID">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.TrainingProgramID">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>