NWEEI/NWEEI/Controllers/Navigation/ProgramsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace NWEEI.Controllers.Navigation
{
    public class ProgramsController : Controller
    {
        public async Task<IActionResult> ProfessionalDevelopment()
        {
            ViewBag.Current = "Professional Development";
            return View();
        }

        // get degrees overview view
        public async Task<IActionResult> Degrees()
        {
            ViewBag.Current = "Degrees";
            return View();
        }

        // get degrees > energy management building controls view
        public async Task<IActionResult> EMBC()
        {
            ViewBag.Current = "Degrees";
            return View();
        }

        // get degrees > water conservation
        public async Task<IActionResult> WaterConservation()
        {
            ViewBag.Current = "Degrees";
            return View();
        }

        // get professional development > custom training
        public async Task<IActionResult> CustomTraining()
        {
            ViewBag.Current = "Professional Development";
            return View();
        }

        // get professional development > building operator certification
        public async Task<IActionResult> BOC()
        {
            ViewBag.Current = "Professional Development";
            return View();
        }

        /*
        // not a currently valid degree
        // get degrees > energy management technician
        public async Task<IActionResult> EnergyMgmt()
        {
            ViewBag.Current = "Degrees";
            return View();
        }
        */
    }
}

NWEEI/NWEEI/Views/Programs/BOC.cshtml
@{
    ViewData["Title"] = "Building Operator Certification";
}

<!-- program title and image -->
<div>
    <div class="boc program-header">
        <div class="program-title">Building Operator Certification</div>
    </div>
</div>

<!-- program overview -->
<div class="container content-section">
    <h3>Building Operator Certification</h3>
    <p>
        The Building Operator Certification (BOC) is an online professional
        development program created by The Northwest Energy Efficiency Council
        (NEEC) and delivered by NWEEI. It is designed for operations and
        maintenance staff working in public or private commercial buildings.
        It provides education to individuals in energy and resource-efficient
        operation of building systems.
    </p>
    <p>
        The BOC registration fee of $1,895 includes the full course series
        of Level I or Level II, a set of course workbooks, project assignments,
        and certificate materials. Some participants may qualify for a cash
        incentive of up to $1,400 provided by
        <a class="font-weight-bold" href="https://energytrust.org/commercial/tools-resources/">
            Energy Trust of Oregon
        </a>
        to help with the cost of completing Level I or Level II BOC training.
    </p>

    <p class="text-center pt-2 font-weight-bold mb-0">
        <a asp-controller="About" asp-for="ContactUs">
            Contact us to learn more about the Building Operator Certification.
        </a>
    </p>
</div>

<!-- certification levels -->
<div class="dark-block">
    <div class="container">
        <div class="content-section">

            <div class="row text-center boc-levels">

                <!-- level 1 -->
                <div class="col-5">
                    <h4>
                        Building Operator Certification
                    </h4>
                    <h5>
                        Level I
                    </h5>
                    <p class="text-white">
                        To receive the Level I certificate, participants must
                        attend eight Level I classes (74 hours), and complete
                        class exams and project assignments at your facility.
                        These hours reflect in-class time as well as project time.
                        The first class is a two-day class.
                    </p>
                </div>

                <!-- divider -->
                <div class="col-2 divider text-center">
                    <hr />
                </div>

                <!-- level 2 -->
                <div class="col-5">
                    <h4>
                        Building Operator Certification
                    </h4>
                    <h5>
                        Level II
                    </h5>
                    <p class="text-white">
                        To receive the Level II certificate, participants must
                        attend four core classes and two elective classes, complete
                        class exams, and assigned projects, for a total of 61 hours.
                        These hours reflect in-class time as well as project time.
                    </p>
                </div>
            </div>

            <!-- learn more: link to BOC site -->
            <div class="row justify-content-center mt-4">
                <h5 class="mb-0">
                    Visit the
                    <a class="dark-block-link"
                       href="https://www.theboc.info/building-operator-training/course-descriptions/">
                        BOC Website
                    </a>
                    to learn about the classes offered for each level.
                </h5>
            </div>
        </div>
    </div>
</div>

<!-- who should attend -->
<div class="container content-section d-flex">
    <img src="~/images/woman-eng_adb_403276685.jpeg" class="content-image" />

    @*backup image*@
    @*<img src="~/images/ctrl-panel_adb_42605852.jpeg" class="content-image" />*@


    <div class="content-info">
        <h4>Who Should Attend?</h4>
        <p>
            The Building Operator Certification is ideal for operations
            and maintenance staff working in public or private commercial
            buildings, including:
        </p>

        <ul class="mb-0">
            <li>Engineers</li>
            <li>Technicians</li>
            <li>Architects</li>
            <li>Facility, Maintenance & Energy Managers</li>
        </ul>
    </div>
</div>

<!-- current schedule -->
<div class="light-block">
    <div class="container">
        <div class="content-section">
            <h4 class="text-center">
                Current Schedule: Level I Summer 2022 Fast Track
            </h4>

            <!-- schedule table -->
            <div>
                <table class="schedule">
                    <thead>
                        <tr>
                            <th style="border-radius: 20px 0px 0px 0px;">Date</th>
                            <th>Class</th>
                            <th style="border-radius: 0px 20px 0px 0px;">Instructor</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>June 22, 2022</td>
                            <td>BOC 1001A: Energy Efficient Operation of Building HVAC Systems</td>
                            <td>Suzanne Marinello</td>
                        </tr>
                        <tr>
                            <td>June 29, 2022</td>
                            <td>BOC 1001B: Energy Efficient Operation of Building HVAC Systems</td>
                            <td>Suzanne Marinello</td>
                        </tr>
                        <tr>
                            <td>July 13, 2022</td>
                            <td>BOC 1002: Measuring & Benchmarking Energy Performance</td>
                            <td>Roger Ebbage</td>
                        </tr>
                        <tr>
                            <td>July 27, 2022</td>
                            <td>BOC 1003: Efficient Lighting Fundamentals</td>
                            <td>Dawn Doberenz</td>
                        </tr>
                        <tr>
                            <td>August 10, 2022</td>
                            <td>BOC 1004: HVAC Controls Fundamentals</td>
                            <td>Suzanne Marinello</td>
                        </tr>
                        <tr>
                            <td>Sept 7, 2022</td>
                            <td>BOC 1005: Indoor Environmental Quality</td>
                            <td>Karen Chase</td>
                        </tr>
                        <tr>
                            <td>August 24, 2022</td>
                            <td>BOC 1006: Common Opportunities for Low-Cost Energy Savings</td>
                            <td>Suzanne Marinello</td>
                        </tr>
                        <tr style="padding-bottom: 1%;">
                            <td>September 14, 2022</td>
                            <td>BOC 2004: Water Efficiency for Building Operators</td>
                            <td>Brenda Cervantes</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<!-- apply / register / learn more -->
<div class="container content-section text-center">
    <h5>
        Contact NWEEI to learn more about the Building Operator Certification.
    </h5>

    <!-- buttons -->
    <div class="container w-75">
        <div class="button-group row">
            <a asp-controller="About" asp-action="ContactUs" class="btn btn-primary">
                Contact Us
            </a>

            <a class="btn btn-primary" asp-controller="Registration" asp-action="Create">Register</a>
        </div>
    </div>

NWEEI/NWEEI/Views/Programs/Degrees.cshtml
@{
    ViewData["Title"] = "2-Year Degrees";
}

<!-- degrees overview -->
<div class="container content-section pt-1">
    <h3>2-Year Degrees at NWEEI</h3>
    <h5 class="pt-3 pb-1">Online Classes and Hands-On Mentorship is the Ideal Combination</h5>
    <p>
        We’ve combined the flexibility and ease of online coursework with hands-on
        training with industry partners in the field to prepare you for a career in
        energy efficiency. Our goal is to provide students with hands-on, high-quality
        experiences with potential employers in your area equal to or better than what
        they’d receive in a college laboratory environment. Apply your knowledge to a
        growing, stable industry in the Pacific Northwest and elevate your career today.
    </p>
</div>

<!-- degree tiles -->
<div class="dark-block">
    <div class="container">
        <div class="content-section">
            <h5 class="text-center pb-3">Select one of NWEEI's degrees to learn more:</h5>
            <div class="container tiles w-75">

                <a class="tile-link" asp-controller="Programs" asp-action="EnergyMgmt">
                    <div class="tile-container">
                        <span class="tile-content">
                            Energy Management Technician
                        </span>
                    </div>
                </a>

                <a class="tile-link" asp-controller="Programs" asp-action="EMBC">
                    <div class="tile-container">
                        <span class="tile-content">
                            Energy Management & Building Controls
                        </span>
                    </div>
                </a>

                <a class="tile-link" asp-controller="Programs" asp-action="WaterConservation">
                    <div class="tile-container">
                        <span class="tile-content">
                            Water Conservation
                        </span>
                    </div>
                </a>
            </div>
        </div>
    </div>
</div>

<!-- contact -->
<div class="container content-section text-center">
    <h4>Have a Question?</h4>
    <h6 class="pt-2">
        <a asp-controller="About" asp-action="ContactUs">Contact us</a> with any
        additional questions you have about NWEEI degree programs.
    </h6>
</div>

NWEEI/NWEEI/Views/Programs/EMBC.cshtml
@{
    ViewData["Title"] = "Energy Management with Building Controls";
}

<!-- degree title and image -->
<div>
    <div class="embc program-header">
        <div class="program-title">Energy Management with Building Controls</div>
    </div>
</div>

<!-- degree overview -->
<div class="container content-section">
    <h3>Energy Management with Building Controls, AAS</h3>
    <p>
        Building Controls technicians work in the fast-growing field of Energy Management.
        Our online, two-year Energy Management with Building Controls degree program will prepare
        you for a rewarding career managing highly technical buildings so they operate efficiently.
        Commercial buildings are responsible for approximately 40% of our national energy consumption
        and the jobs managing and optimizing building energy and water performance will help shape
        our environmental future.
    </p>

    <p class="pt-2">
        Once you're enrolled in the Building Controls program, you can optionally add the Building Energy
        Controls Apprenticeship (BECA) program. Apprentices may complete an Associate of Applied Science
        2-Year degree in Energy Management with Controls with the first year dedicated to core learning
        at Lane Community College, and the second year focusing on more advanced courses that run
        concurrently with apprenticeship hours at BECA. This program now also has a Registered
        Apprenticeship Program in the state of Oregon, which includes paid 2000 hours of on-the-job
        training in a local building in the student’s area. For more information contact Roger Ebbage
        at (541) 463-3670.

        <a class="font-weight-bold" href="https://becajobs.org/">
            Visit the BECA Jobs website to learn more.
        </a>
    </p>
</div>

<!-- what you'll learn -->
<div class="dark-block">
    <div class="container">
        <div class="content-section">
            <h4>What You'll Learn</h4>
            <p>Graduates of the program are able to:</p>

            <div class="content-highlight-container row">
                <div class="content-highlight">
                    <h6>Building Automation</h6>
                    <p>
                        Learn modules and electronics commonly used to
                        implement building automation.
                    </p>
                </div>

                <div class="content-highlight">
                    <h6>HVAC & Lighting</h6>
                    <p>
                        Analyze a variety of commercial HVAC and lighting systems
                        from a controls perspective.
                    </p>
                </div>

                <div class="content-highlight">
                    <h6>Control Systems</h6>
                    <p>Diagnose and troubleshoot existing control systems.</p>
                </div>
            </div>

            <div class="content-highlight-container row">
                <div class="content-highlight">
                    <h6>Energy Efficiency</h6>
                    <p>
                        Recommend energy efficiency and alternative control
                        solutions for high energy consuming buildings.
                    </p>
                </div>

                <div class="content-highlight">
                    <h6>Energy Consumption</h6>
                    <p>
                        Understand the interactions between energy consuming
                        building systems and implement control changes based
                        on that understanding.
                    </p>
                </div>

                <div class="content-highlight">
                    <h6>Residential & Commercial Energy</h6>
                    <p>
                        Use typical control system management software to evaluate
                        energy use patterns for residential and commercial buildings.
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- personal attention from engaging faculty -->
<div class="container content-section d-flex">
    <img src="~/images/stories/trio-in-mech-room.jpg" class="content-image" />

    <div class="content-info">
        <h4>Personal Attention from Engaging Faculty</h4>
        <p>
            Lane offers students the best of both worlds: a wide variety
            of courses from which to choose and small class sizes. You’ll
            never take a class with more than 40 students, and most of your
            Energy Management courses will have just 15-20 students. Your classes
            will always be taught by an instructor with professional experience,
            and not a grad student. Program instructors and staff use their extensive
            experience and industry and alumni relationships to ensure your classes
            connect you to the real world. Program staff are always there to assist
            with whatever your needs may be.
        </p>
    </div>
</div>

<!-- job opportunities -->
<div class="light-block">
    <div class="container">
        <div class="content-section">
            <h4>Job Opportunities</h4>
            <p>
                Through local, regional, and national networking opportunities,
                our graduates meet business leaders directly. Our graduates work in a 
                wide variety of disciplines and may apply to work for a variety of different
                employers such as engineering firms, lighting companies, public and private
                utilities, energy equipment companies, and departments of energy.
                Positions include:
            </p>

            <div class="content-highlight-container row">
                <div class="content-highlight">
                    <h6>Building Operator</h6>
                </div>

                <div class="content-highlight">
                    <h6>Control System Specialist, Technician</h6>
                </div>

                <div class="content-highlight">
                    <h6>Weatherization Installer and Technician</h6>
                </div>
            </div>

            <div class="content-highlight-container row">
                <div class="content-highlight">
                    <h6>Energy Auditor</h6>
                </div>

                <div class="content-highlight">
                    <h6>Energy Resource Analyst</h6>
                </div>

                <div class="content-highlight">
                    <h6>Building Automation</h6>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- apply / register / learn more -->
<div class="container content-section text-center">
    <h5>
        Apply to Lane Community College and register for the
        Energy Management with Building Controls program today.
    </h5>

    <!-- buttons -->
    <div class="button-group row">
        <a href="https://inside.lanecc.edu/science/energy-management-building-controls" class="btn btn-primary">
            Learn More
        </a>

        <a href="https://inside.lanecc.edu/apply" class="btn btn-primary">Apply to LCC</a>

        <a class="btn btn-primary" asp-controller="Registration" asp-action="Create">Register for Program</a>
    </div>
</div>

NWEEI/NWEEI/Views/Programs/EnergyMgmt.cshtml
@{
    ViewData["Title"] = "Energy Management Technician";
}

<!-- degree title and image -->
<div>
    <div class="energy-mgmt program-header">
        <div class="program-title">Energy Management</div>
    </div>
</div>

<!-- degree overview -->
<div class="container content-section">
    <h3>Energy Management Technician, AAS</h3>
    <p>
        Energy Management is a growing technical industry. Not only is it a viable
        way to maintain a high level of energy efficiency as technology and needs change,
        it’s a great field for those interested in elevating their technical and mechanical
        careers. For more than 30 years, NWEEI and LCC have successfully provided
        significant opportunities to train professional technicians who can immediately
        contribute to energy, water and cost savings in their communities.
        Through this online program, students will learn how residential
        and commercial building systems consume energy by understanding how they
        work and the interaction between one another. Students will be able to
        evaluate and measure consumption and make an informed recommendation on
        building system energy efficiency improvements. Employment is found with
        government, utilities, engineering firms, school districts, community action
        programs, and residential weatherization practitioners.
    </p>
</div>

<!-- what you'll learn -->
<div class="dark-block">
    <div class="container">
        <div class="content-section">
            <h4>What You'll Learn</h4>
            <p>Graduates of the program are able to:</p>

            <div class="content-highlight-container row">
                <div class="content-highlight">
                    <h6>Evaluate Usage Patterns</h6>
                    <p>
                        Evaluate energy use patterns for residential and commercial
                        buildings and recommend efficiency measures and renewable
                        energy solutions for high energy consuming buildings.
                    </p>
                </div>

                <div class="content-highlight">
                    <h6>Interpret Energy Concepts</h6>
                    <p>
                        Interpret the concepts of a problem-solving task, and, using mathematics,
                        translate concepts into energy related projects.
                    </p>
                </div>

                <div class="content-highlight">
                    <h6>Understand Energy Consumption</h6>
                    <p>
                        Understand the interaction between energy consuming building
                        systems and make energy use reduction recommendations based on
                        that understanding.
                    </p>
                </div>
            </div>

            <div class="content-highlight-container row">
                <div class="content-highlight">
                    <h6>Analyze Data</h6>
                    <p>
                        Develop and evaluate inferences and predictions based on collected data.
                    </p>
                </div>

                <div class="content-highlight">
                    <h6>Create Reports</h6>
                    <p>
                        Construct energy evaluation technical reports and make
                        presentations for potential project implementation.
                    </p>
                </div>

                <div class="content-highlight">
                    <h6>Read Blueprints</h6>
                    <p>
                        Read and analyze building blueprints including floor, mechanical,
                        and electrical plans.
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- hands on mentorship -->
<div class="container content-section d-flex">
    <img src="~/images/group_adb_491280583.jpeg" class="content-image" />

    <div class="content-info">
        <h4>Hands On Mentorship</h4>
        <p>
            Part of this program includes a mentorship. Students will apply their
            knowledge in hands-on training opportunities at one of our partner
            organizations in Oregon and Washington. Partners include energy service
            departments at public utilities like EWEB, EPUD, Lane Electric, Salem Electric
            Central Oregon Coop, Ashland Electric and many others. This part of the
            degree program provides students with invaluable opportunities to make
            industry connections that can support or provide potential employment opportunities.
        </p>
    </div>
</div>

<!-- job opportunities -->
<div class="light-block">
    <div class="container">
        <div class="content-section">
            <h4>Job Opportunities</h4>
            <p>
                Graduates of our Energy Management degree find employment in a wide variety
                of disciplines and may work for a diverse number of employers such as engineering
                firms, lighting companies, public and private utilities, energy equipment companies,
                and departments of energy. Positions include:
            </p>

            <div class="content-highlight-container row">
                <div class="content-highlight">
                    <h6>Energy Program Coordinator</h6>
                </div>

                <div class="content-highlight">
                    <h6>Energy Analyst</h6>
                </div>

                <div class="content-highlight">
                    <h6>Commissioning Technician</h6>
                </div>
            </div>

            <div class="content-highlight-container row">
                <div class="content-highlight">
                    <h6>Control System Specialist</h6>
                </div>

                <div class="content-highlight">
                    <h6>Building Operator</h6>
                </div>

                <div class="content-highlight">
                    <h6>Weatherization Installer and Technician</h6>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- apply / register / learn more -->
<div class="container content-section text-center">
    <h5>
        Apply to Lane Community College and register for the
        Energy Management and Building Controls program today.
    </h5>

    <!-- buttons -->
    <div class="button-group row">
        <a href="https://catalog.lanecc.edu/preview_program.php?catoid=9&poid=857" class="btn btn-primary">
            Learn More
        </a>

        <a href="https://inside.lanecc.edu/apply" class="btn btn-primary">Apply to LCC</a>

        <a class="btn btn-primary" asp-controller="Registration" asp-action="Create">Register for Program</a>
    </div>
</div>

NWEEI/NWEEI/Views/Programs/ProfessionalDevelopment.cshtml
@{
    ViewData["Title"] = "Professional Development";
}

<!-- professional development overview -->
<div class="container content-section" style="padding-top:1%;">
    <h3>Professional Development at NWEEI</h3>
    <p>
        Through partnerships with various organizations, we are able to deliver training
        to individuals seeking professional development and employers who want to support
        up-skill opportunities for their employees.
    </p>
</div>

<!-- training/certification tiles -->
<div class="dark-block">
    <div class="container">
        <div class="content-section">
            <h5 class="text-center pb-3">Select one of NWEEI's training programs to learn more:</h5>
            <div class="container tiles w-50">

                <a class="tile-link" asp-controller="Programs" asp-action="BOC">
                    <div class="tile-container">
                        <span class="tile-content">
                            Building Operator Certification
                        </span>
                    </div>
                </a>

                <a class="tile-link" asp-controller="TrainingProgram" asp-action="CustomTraining">
                    <div class="tile-container">
                        <span class="tile-content">
                            Custom Training
                        </span>
                    </div>
                </a>
            </div>
        </div>
    </div>
</div>

<!-- contact -->
<div class="container content-section text-center">
    <h4>Have a Question?</h4>
    <h6 class="pt-2">
        <a asp-controller="About" asp-action="ContactUs">Contact us</a> with any
        additional questions you have about professional development at NWEEI.
    </h6>
</div>